### ISSUE TITLE
Can't start the container

### ISSUE THREAD

**Issue by igr** [wedeploy/demo-nodejs#1]
```

h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Linux 4.4.15-moby
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! node v6.5.0
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! npm  v3.10.6
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! code ELIFECYCLE
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! boilerplate-nodejs@1.0.0 start: `node index.js`
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Exit status 1
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Make sure you have the latest version of node.js and npm installed.
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Failed at the boilerplate-nodejs@1.0.0 start script 'node index.js'.
h22.pscenario42.wedeploy.me[03d7a76] npm ERR!
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! If you do, this is most likely a problem with the boilerplate-nodejs package,
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! not with npm itself.
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! You can get information on how to open an issue for this project with:
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Tell the author that this fails on your system:
h22.pscenario42.wedeploy.me[03d7a76] npm ERR!     node index.js
h22.pscenario42.wedeploy.me[03d7a76] npm ERR!     npm bugs boilerplate-nodejs
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Or if that isn't available, you can get their info via:
h22.pscenario42.wedeploy.me[03d7a76] npm ERR!     npm owner ls boilerplate-nodejs
h22.pscenario42.wedeploy.me[03d7a76] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Linux 4.4.15-moby
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! There is likely additional logging output above.
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! node v6.5.0
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! path npm-debug.log.79876370
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! npm  v3.10.6
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! code EROFS
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! errno -30
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! syscall open
h22.pscenario42.wedeploy.me[03d7a76]
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! rofs EROFS: read-only file system, open 'npm-debug.log.79876370'
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! rofs This is most likely not a problem with npm itself
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! rofs
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! rofs and is related to the file system being read-only.
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! rofs that don't support symlinks, give this error.
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! rofs Often virtualized file systems, or other file systems
h22.pscenario42.wedeploy.me[03d7a76]
h22.pscenario42.wedeploy.me[03d7a76] npm ERR! Please include the following file with any support request:
h22.pscenario42.wedeploy.me[03d7a76] npm ERR!     /wedeploy-container/npm-debug.log
h22.pscenario42.wedeploy.me[8e0fc3e] module.js:457
h22.pscenario42.wedeploy.me[8e0fc3e]     throw err;
h22.pscenario42.wedeploy.me[8e0fc3e]     ^
h22.pscenario42.wedeploy.me[8e0fc3e]
h22.pscenario42.wedeploy.me[8e0fc3e] Error: Cannot find module 'express'
h22.pscenario42.wedeploy.me[8e0fc3e]     at Function.Module._resolveFilename (module.js:455:15)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Module.require (module.js:483:17)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Function.Module._load (module.js:403:25)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Object.<anonymous> (/wedeploy-container/index.js:1:77)
h22.pscenario42.wedeploy.me[8e0fc3e]     at require (internal/module.js:20:19)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Module._compile (module.js:556:32)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Object.Module._extensions..js (module.js:565:10)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Function.Module._load (module.js:424:3)
h22.pscenario42.wedeploy.me[8e0fc3e]     at tryModuleLoad (module.js:432:12)
h22.pscenario42.wedeploy.me[8e0fc3e]     at Module.load (module.js:473:32)
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! Linux 4.4.15-moby
h22.pscenario42.wedeploy.me[8e0fc3e]
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! node v6.5.0
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! npm  v3.10.6
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! code ELIFECYCLE
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! Exit status 1
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! boilerplate-nodejs@1.0.0 start: `node index.js`
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! Failed at the boilerplate-nodejs@1.0.0 start script 'node index.js'.
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR!
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! If you do, this is most likely a problem with the boilerplate-nodejs package,
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! Make sure you have the latest version of node.js and npm installed.
h22.pscenario42.wedeploy.me[8e0fc3e] npm ERR! Tell the author that this fails on your system:

```

**Comment by cirocosta** [comment]
Hey @igorspasic , could you provide the steps to reproduce this? It looks like `we build` wasn't performed (as `express` can't be found in `node_modules`)

**Comment by igr** [comment]
Very simple @cirocosta : just create project with nodejs container. I was using this one.

I did `build-images` locally.

**Comment by igr** [comment]
`we build` made a change :)
